apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: svc-simple-api-hs
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: simpleapi
  sessionAffinity: None
  type: ClusterIP
