apiVersion: v1
kind: Service
metadata:
  name: svc-simple-api
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: simpleapi
  sessionAffinity: None
  type: ClusterIP
status: {}
